"""add session_id to events

Revision ID: e119cb08bd10
Revises: c0a2cfe62edc
Create Date: 2025-09-16 21:40:09.036872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e119cb08bd10'
down_revision: Union[str, Sequence[str], None] = 'c0a2cfe62edc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('session_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'session_id')
    # ### end Alembic commands ###
